### ISSUE TITLE
New Langs add not show

### ISSUE THREAD

**Issue by lalrochhara** [Divkix/Alita_Robot#175]
## Checklist
- [ ✓] I am sure the error is coming from Bot's code and not elsewhere.
- [ ] I have searched in the issue tracker for similar bug reports, including closed ones.
- [ ] I ran `pip3 install -U https://github.com/DivideProjects/Alita_Robot/archive/master.zip` and reproduced the issue using the latest development version.
- [ ] I'n not here to spam and show that I'm stupid.

## Description
A clear and concise description of the problem.
What is happening?
Why do you think it is happening?

I add new language(edite en.yml file and add new file for this, one is work) to my alita forks, one is our language Mizo, other one is turkey but turkey isn't showing my bot? I don't know how to fix this, i search through all modules but I can't find where to fix, also there's no errors log in heroku too, please can you help me?
Sorry for my silly pull request this is my first time.
Thanks in advance.

## Traceback
The full traceback (if applicable).

**Comment by annihilatorrrr** [comment]
add it here https://github.com/DivideProjects/Alita_Robot/blob/main/locales/
then name it as mizo.yml and your ENV VAR for locales should be mizo and it will work , also u need to hav all the strings translated
