### ISSUE TITLE
Reporting InlineKeyboardMarkup issues on notes and filters. 

### ISSUE THREAD

**Issue by ghost** [Divkix/Alita_Robot#186]
Notes and filters with buttons are  not getting. When we have  saved. I have attached. error logs as file with this. [InlineKeyboardMarkup] is also not defined on it. 
[nazriyanazeembot-logs-1639011784617.txt](https://github.com/DivideProjects/Alita_Robot/files/7681447/nazriyanazeembot-logs-1639011784617.txt)

**Comment by annihilatorrrr** [comment]
Ok we will get into it :) thanks for reporting.

**Comment by annihilatorrrr** [comment]
Ok bug has been fixed !
We will release it after some pyrogram updates i.e. tommorow or day after tomorrow :)

**Comment by ghost** [comment]
It's mine pleasure welcome bro. :)
