### ISSUE TITLE
requirements.txt missed?

### ISSUE THREAD

**Issue by 0gk** [Divkix/Alita_Robot#297]
Please excuse me if I didn't understand something. requirements.txt file is missing in the project root and in other folders too.

**Comment by Divkix** [comment]
We use poetry for this project. It’s an advanced package manager version based on pip.

More info can be found here:
https://python-poetry.org/

**Comment by 0gk** [comment]
Thank you! I just didn't find information about this in the project description and I remember that earlier there was requirements.txt.
