### ISSUE TITLE
Getting KeyError: 'en-US'

### ISSUE THREAD

**Issue by rsoorajs** [Divkix/Alita_Robot#5]
Can you solve this error ?
i setup everything,including redis and postgres ,bot is just sending its start msg

`Bot started on Pyrogram v1.0.7 (Layer - 117)`

`Loaded Plugins:`
`['admin', 'approve', 'blacklist', 'covid', 'fun', 'language', 'locks', 'notes', 'purges', 'reporting', 'rules', 'translate', 'utils', 'wikipedia']`
`Redis Keys Loaded:`
`[b'SUPPORT_STAFF', b'ADMINDICT', b'BOT_ID']`

after that bot suddenly stopping.

the log screenshot is attaching below

![IMG_20201029_215933_790](https://user-images.githubusercontent.com/20116017/97603359-5e6fbc00-1a32-11eb-8098-3e7b62669c96.jpg)

**Comment by Divkix** [comment]
Reproduce the steps you did

**Comment by rsoorajs** [comment]
i just put my own redis and postgres database url..

and i just ran threw sudo docker-compose up after filling out the env file

**Comment by rsoorajs** [comment]
i didnt touched `/alita/sample_config.py` this file nor changed to `config.py`

since i am using docker i filled details in alita.env by changing sample.env to alita.env

**Comment by Divkix** [comment]
Could you show your alita.env file without the app id, hash and token?

**Comment by telegrambotdev** [comment]
> Could you show your alita.env file without the app id, hash and token?

![IMG_20201029_224015_492](https://user-images.githubusercontent.com/20116017/97607999-c07ef000-1a37-11eb-9fa3-b3207d1e97ca.jpg)

**Comment by telegrambotdev** [comment]
![IMG_20201029_224555_263](https://user-images.githubusercontent.com/20116017/97608581-89f5a500-1a38-11eb-921a-3d64d8d73926.jpg)

**Comment by Divkix** [comment]
> when the workers was 8 i still got the same error

It's not an issue with workers.

I think maybe your `alita.env` isn't set correctly because when I run the bot, it works.

**Comment by rsoorajs** [comment]
let me check
